AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - "lib/generators/**/*"
    - "spec/**/*" # stuff for later
    - "lib/permisi/permission_util.rb" # The necessary evil (for now)

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# Stuff for later
Documentation:
  Enabled: false
