name: RuboCop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run RuboCop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-check # Default is github-pr-check
      run: bundle exec rubocop
